In [3]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

In [4]:
# removed first row and column
# df = pd.read_csv ("/Users/kellyfang/Downloads/11.154/separation_data_set.csv")
df = pd.read_csv ("separation_data_set.csv")
df["lat"] = ""
df["lon"] = ""

display(df)

,AGE,GENDER,COO,DATE_APPREHENDED,REFERRAL_DATE,DATE_ORR_APPROVED,REFERRING OFFICE,FACILITY_APPROVED,REUNITIED_SEP_PARENTS,UAC STATUS,Date Discharged,Reason fo Separation,lat,lon
0,16,M,Brazil,2/15/2018,2/15/2018,2/17/2018,El Paso (ELP),Heartland Intl Childrens RC,Discharged Under other approp circumstances,DISCHARGED,7/8/2018,Zero Tolerance Policy,,
1,17,F,Romania,5/27/2018,5/29/2018,5/30/2018,Harlingen (SNA),Homestead,Discharged Under other approp circumstances,DISCHARGED,6/4/2018,Zero Tolerance Policy,,
2,11,M,Mexico,2/1/2018,2/6/2018,2/8/2018,San Diego (SND),Cayuga Centers,Discharged Under other approp circumstances,DISCHARGED,2/2/2019,Zero Tolerance Policy,,
3,15,M,Mexico,2/2/2018,2/6/2018,2/8/2018,San Diego (SND),Cayuga Centers,Discharged Under other approp circumstances,DISCHARGED,2/2/2019,Zero Tolerance Policy,,
4,8,M,Honduras,6/2/2018,6/4/2018,6/5/2018,NaN,Cayuga Centers,Discharged Under other approp circumstances,DISCHARGED,11/7/2018,Zero Tolerance Policy,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3165,14,M,Guatemala,1/28/2019,1/30/2019,2/1/2019,El Paso (ELP),Homestead,Still In Care,ADMITTED,NaN,Parent Criminal History,,
3166,17,M,Guatemala,1/14/2019,1/16/2019,1/16/2019,Harlingen (SNA),Southwest Key Casa Padre,Other approp. Circumstances,DISCHARGED,3/21/2019,Parent Criminal History,,
3167,1,F,El Salvador,12/10/2018,12/12/2018,12/14/2018,"Phoenix, AZ (PHO)",Bethany Christian Services Maryland,Reunited with Sep. Parent,DISCHARGED,3/15/2019,Other,,
3168,16,M,Guatemala,12/6/2018,1/2/2019,1/3/2019,San Diego (SND),Southwest Key San Diego,Reunited with Sep. Parent,DISCHARGED,1/8/2019,Adult Relative‐ Other,,
3169,9,M,Guatemala,12/16/2018,12/19/2018,12/22/2018,"Phoenix, AZ (PHO)",BCFS Raymondville,Still In Care,ADMITTED,NaN,Unable to verify familial\r\nrelationship.,,

In [5]:
from datetime import datetime

def days_between(d1, d2):
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)


start = df["DATE_APPREHENDED"]
end = df["Date Discharged"]


duration_col = []

for i in range(len(df)):
    d1 = start[i]
    d2 = end[i]
    
    if type(d2) == float or len(d2)<5:
        duration_col.append(0)
    else:
        split1 = d1.split("/")
       
        date1 = split1[2] + "-" + split1[0]+"-" + split1[1]
        

        split2 = d2.split("/")
        date2 = split2[2] + "-" + split2[0]+"-" + split2[1]
    
        dur = days_between(date1,date2)
        
        duration_col.append(dur)
        
df_new = df.assign(Duration = duration_col)
display(df_new)

,AGE,GENDER,COO,DATE_APPREHENDED,REFERRAL_DATE,DATE_ORR_APPROVED,REFERRING OFFICE,FACILITY_APPROVED,REUNITIED_SEP_PARENTS,UAC STATUS,Date Discharged,Reason fo Separation,lat,lon,Duration
0,16,M,Brazil,2/15/2018,2/15/2018,2/17/2018,El Paso (ELP),Heartland Intl Childrens RC,Discharged Under other approp circumstances,DISCHARGED,7/8/2018,Zero Tolerance Policy,,,143
1,17,F,Romania,5/27/2018,5/29/2018,5/30/2018,Harlingen (SNA),Homestead,Discharged Under other approp circumstances,DISCHARGED,6/4/2018,Zero Tolerance Policy,,,8
2,11,M,Mexico,2/1/2018,2/6/2018,2/8/2018,San Diego (SND),Cayuga Centers,Discharged Under other approp circumstances,DISCHARGED,2/2/2019,Zero Tolerance Policy,,,366
3,15,M,Mexico,2/2/2018,2/6/2018,2/8/2018,San Diego (SND),Cayuga Centers,Discharged Under other approp circumstances,DISCHARGED,2/2/2019,Zero Tolerance Policy,,,365
4,8,M,Honduras,6/2/2018,6/4/2018,6/5/2018,NaN,Cayuga Centers,Discharged Under other approp circumstances,DISCHARGED,11/7/2018,Zero Tolerance Policy,,,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3165,14,M,Guatemala,1/28/2019,1/30/2019,2/1/2019,El Paso (ELP),Homestead,Still In Care,ADMITTED,NaN,Parent Criminal History,,,0
3166,17,M,Guatemala,1/14/2019,1/16/2019,1/16/2019,Harlingen (SNA),Southwest Key Casa Padre,Other approp. Circumstances,DISCHARGED,3/21/2019,Parent Criminal History,,,66
3167,1,F,El Salvador,12/10/2018,12/12/2018,12/14/2018,"Phoenix, AZ (PHO)",Bethany Christian Services Maryland,Reunited with Sep. Parent,DISCHARGED,3/15/2019,Other,,,95
3168,16,M,Guatemala,12/6/2018,1/2/2019,1/3/2019,San Diego (SND),Southwest Key San Diego,Reunited with Sep. Parent,DISCHARGED,1/8/2019,Adult Relative‐ Other,,,33
3169,9,M,Guatemala,12/16/2018,12/19/2018,12/22/2018,"Phoenix, AZ (PHO)",BCFS Raymondville,Still In Care,ADMITTED,NaN,Unable to verify familial\r\nrelationship.,,,0

In [6]:
h = df_new[["FACILITY_APPROVED", "UAC STATUS"]].copy()
discharge_binary = []
for i in h["UAC STATUS"]:
    if i == "DISCHARGED":
        discharge_binary.append(1)
    else:
        discharge_binary.append(0)
        
df_discharge = pd.DataFrame({'discharge_rate':discharge_binary})

df_discharge_rate = h.join(df_discharge).groupby(["FACILITY_APPROVED"]).mean()

In [7]:
df_n = df_new[["FACILITY_APPROVED", "lat", "lon","Duration"]].copy()
display(df_n)

                        FACILITY_APPROVED lat lon  Duration
0             Heartland Intl Childrens RC               143
1                               Homestead                 8
2                          Cayuga Centers               366
3                          Cayuga Centers               365
4                          Cayuga Centers               158
...                                   ...  ..  ..       ...
3165                            Homestead                 0
3166             Southwest Key Casa Padre                66
3167  Bethany Christian Services Maryland                95
3168              Southwest Key San Diego                33
3169                    BCFS Raymondville                 0

[3170 rows x 4 columns]

In [8]:
df_avg_duration = df_n.groupby(["FACILITY_APPROVED"]).mean()

In [9]:
stats_df = df_avg_duration.join(df_discharge_rate)
display(stats_df)

                                Duration  discharge_rate
FACILITY_APPROVED
A New Leaf – Dorothy Mitchell  63.600000        1.000000
A New Leaf – Peterson          51.200000        1.000000
Abbott House Shelter           69.038462        1.000000
Abbott House TFC               85.000000        1.000000
BCFS Baytown                   75.951613        0.983871
...                                  ...             ...
St. PJs TFC                    40.000000        0.666667
The Villages                   66.857143        1.000000
Upbring                        67.457143        0.885714
Youth For Tomorrow             54.681818        0.954545
Youthcare                      85.625000        1.000000

[100 rows x 2 columns]

In [10]:
stats_df.to_csv('../facility_stats.csv')